name = "newsnowyf"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2026-01-05"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow-db"
database_id = "2dda7712-6881-4b62-bfcf-d6bb83005c19"
